#sudo: false

language: cpp

compiler:
  - gcc
  - clang

dist: jammy
 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-12
    - valgrind
    - libicu-dev

before_install:
  - sudo apt-get -y update
  - sudo apt-get install -y g++12
  - sudo apt-get install -y valgrind
  - sudo apt-get install -y libicu-dev
  
install:
  # g++
  - if [ "$CXX" = "g++" ]; then export CXX="g++-12"; fi
  
before_script: 
  # display cpu info
  - cat /proc/cpuinfo
  - $CXX --version
  - echo "CXX="$CXX
  - mkdir obj
  
script: 
  - make
  - ./MenaceTesting 
 # valgrind --leak-check=full --show-reachable=yes --track-origins=yes --error-exitcode=1  ./MenaceTesting exclude:perft
  - cd test/EloRegressionTest/
  - ./eloRegressionTest.sh

 
notifications:
  email:
    recipients:
      - pcflowers@live.com
