sudo: required

language: cpp

compiler:
  - gcc
  - clang

dist: jammy
 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-12
    - libicu-dev

before_install:
  # install Ubuntu Multiarch-Support 2.27
  - sudo wget http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/multiarch-support_2.27-3ubuntu1.6_amd64.deb
  - sudo dpkg -i multiarch-support_2.27-3ubuntu1.6_amd64.deb
  # install libicu60
  - sudo wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu60_60.2-3ubuntu3_amd64.deb
  - sudo dpkg -i libicu60_60.2-3ubuntu3_amd64.deb
  # install libicu52
  - sudo wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu52_52.1-3ubuntu0.8_amd64.deb
  - sudo dpkg -i libicu52_52.1-3ubuntu0.8_amd64.deb
  - sudo apt-get install -y g++12
  - sudo apt-get install -y libicu-dev
  - sudo apt-get install -y build-essential
  
install:
  # g++
  - if [ "$CXX" = "g++" ]; then export CXX="g++-12"; fi
  
before_script: 
  # display cpu info
  - cat /proc/cpuinfo
  - $CXX --version
  - echo "CXX="$CXX
  - mkdir obj
  
script: 
  - make
  - ./MenaceTesting
  - cd test/EloRegressionTest/
  - ./eloRegressionTest.sh

 
notifications:
  email:
    recipients:
      - pcflowers@live.com
